microservice-chart:
  namespace: "nodo"
  image:
    repository: ghcr.io/pagopa/pagopa-stand-in-manager
    tag: "0.2.1"
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
    replicas: 1
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weuuat.nodo.internal.uat.platform.pagopa.it"
    path: /pagopa-stand-in-manager/(.*)
  serviceAccount:
    name: "nodo-workload-identity"
  azure:
    workloadIdentityClientId: <workload-identity-client-id-set-automatically-by-gha>
  podAnnotations: { }
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.25"
    limits:
      memory: "768Mi"
      cpu: "0.5"
  autoscaling:
    enable: false
  envConfig:
    WEBSITE_SITE_NAME: 'pagopa-stand-in-manager' # required to show cloud role name in application insights
    TZ: "Europe/Rome"
    ENV: 'uat'
    APP_LOGGING_LEVEL: 'INFO'
    DEFAULT_LOGGING_LEVEL: 'INFO'
    CORS_CONFIGURATION: '{"origins": ["*"], "methods": ["*"]}'
    SPRING_DATASOURCE_URL: "jdbc:postgresql://nodo-db.u.internal.postgresql.pagopa.it:6432/nodo?prepareThreshold=0"
    SPRING_DATASOURCE_USERNAME: "cfg"
    API_CONFIG_CACHE_BASE_PATH: "https://api.uat.platform.pagopa.it/api-config-cache/p/v1"
    DATA_EXPLORER_URL: "https://pagopaudataexplorer.westeurope.kusto.windows.net"
    DATA_EXPLORER_CLIENT_ID: "74ae19a9-1309-4751-888e-48f85935622e"
    DATA_EXPLORER_TENANT_ID: "7788edaf-0346-4068-9d79-c868aed15b3d"
    DATA_EXPLORER_DB_NAME: "re"
    COSMOS_ENDPOINT: "https://pagopa-u-weu-nodo-standin-cosmos-account.documents.azure.com:443/"
    FORWARDER_URL: "https://api.uat.platform.pagopa.it/pagopa-node-forwarder/api/v1/forward"
    AWS_REGION: "eu-south-1"
    CONFIG_REFRESH_CRON: "0 * * * * *"
    NODO_MONITOR_CRON: "0 */5 * * * *"
    NODO_CALC_CRON: "30 */5 * * * *"
    STATION_MONITOR_CRON: "15 */5 * * * *"
    STATION_CALC_CRON: "45 */5 * * * *"
    ADDER_SLOT_MINUTES: "5"
    ADDER_SLOT_FAULT_THRESHOLD: "50"
    ADDER_RANGE_MINUTES: "30"
    ADDER_RANGE_FAULT_THRESHOLD: "50"
    ADDER_TOTAL_DAYTIME_TRAFFIC_THRESHOLD: "5"
    ADDER_TOTAL_NIGHTTIME_TRAFFIC_THRESHOLD: "10"
    NIGHTTIME_START_HOURS: "22"
    NIGHTTIME_START_MINUTES: "0"
    NIGHTTIME_END_HOURS: "6"
    NIGHTTIME_END_MINUTES: "0"
    REMOVER_SLOT_MINUTES: "60"
    REMOVER_SLOT_FAULT_LIMIT: "6"
    EXCLUDED_STATIONS: "10387150963_01"
    OTEL_SERVICE_NAME: "pagopastandinmanager"
    OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=uat"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_TRACES_EXPORTER: otlp
    OTEL_METRICS_EXPORTER: otlp
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
    STAND_IN_TX_NAME: "nodo-dei-pagamenti-stand-in"
  envFieldRef:
    APP_NAME: "metadata.labels['app.kubernetes.io/instance']"
    APP_VERSION: "metadata.labels['app.kubernetes.io/version']"
  envSecret:
    # required
    APPLICATIONINSIGHTS_CONNECTION_STRING: "azure-insight-connection-string"
    OTEL_EXPORTER_OTLP_HEADERS: "elastic-apm-secret-token"
    SPRING_DATASOURCE_PASSWORD: "db-cfg-password"
    API_CONFIG_CACHE_API_KEY: "api-config-cache-subscription-key-string"
    AWS_ACCESS_KEY_ID: "pagopa-aws-access-id"
    AWS_SECRET_ACCESS_KEY: "pagopa-aws-secret-access-key"
    AWS_SES_USER: "standin-aws-ses-user"
    AWS_MAILTO: "standin-mail-to"
    COSMOS_KEY: "cosmos-standin-account-key"
    FORWARDER_KEY: "node-forwarder-subscription-key-string"
    STAND_IN_TX_CONNECTION_STRING: "nodo-dei-pagamenti-stand-in-tx-connection-string-key"
    DATA_EXPLORER_CLIENT_SECRET: "dataexplorer-client-secret"
  keyvault:
    name: "pagopa-u-nodo-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  tmpVolumeMount:
    create: true
  tolerations:
    - key: dedicated
      operator: Equal
      value: "nodo"
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: false
